package consts

const (
	ErrorEmptyPhone               = "Empty phone"
	ErrorEmpty2FAPassword         = "Empty 2FA password"
	ErrorEmptyLoginCode           = "Empty login code"
	ErrorSignUpNotSupported       = "Sign up is not supported"
	ErrorEmptySessionPassword     = "Empty session password"
	ErrorEmptyTelegramAPIHash     = "Empty Telegram API hash"
	ErrorTelegramAPIHashLength    = "Telegram API hash length must be 32, got %d"
	ErrorTelegramAPIHashMustBeHex = "Telegram API hash must be hex"
	ErrorGetTerminalState         = "Get terminal state: %w"
	ErrorDisableTerminalEcho      = "Disable terminal echo: %w"

	ErrorOpenFile              = "Open %s: %w"
	ErrorDotEnvMissingEqual    = "Parse %s line %d: missing ="
	ErrorDotEnvInvalidKey      = "Parse %s line %d: invalid key"
	ErrorSetEnv                = "Set env %s: %w"
	ErrorReadFile              = "Read %s: %w"
	ErrorTelegramAPIIDInteger  = "Telegram API ID must be integer: %w"
	ErrorTelegramAPIIDPositive = "Telegram API ID must be positive"

	ErrorInvalidLogLevel = "Invalid log level: %s"

	ErrorInitializeLogin = "Initialize login: %w"
	ErrorGetSelf         = "Get self: %w"
	ErrorTelegramPlugin  = "Telegram plugin error"

	ErrorDeriveSessionKey              = "Derive session key: %w"
	ErrorDeriveSessionKeyLength        = "Derive session key length: %d"
	ErrorCreateSessionCipher           = "Create session cipher: %w"
	ErrorCreateSessionGCM              = "Create session gcm: %w"
	ErrorReadSessionFile               = "Read session file %s: %w"
	ErrorEncryptPlaintextSessionFile   = "Encrypt plaintext session file %s: %w"
	ErrorWriteEncryptedSessionFile     = "Write encrypted session file %s: %w"
	ErrorInvalidSessionFileName        = "Invalid session file name %q"
	ErrorCheckSessionPath              = "Check session path %s: %w"
	ErrorSessionPathEscapesDataDir     = "Session path escapes data dir: %s"
	ErrorSessionDirCurrentDir          = "Session dir must not be current dir"
	ErrorCreateSessionDir              = "Create session dir %s: %w"
	ErrorCheckSessionDir               = "Check session dir %s: %w"
	ErrorSessionDirSymlink             = "Session dir must not be symlink: %s"
	ErrorSessionPathNotDir             = "Session path is not dir: %s"
	ErrorDecodeSessionFile             = "Decode session file %s: %w"
	ErrorMalformedEncryptedSessionFile = "Malformed encrypted session file %s"
	ErrorDecodeSessionSalt             = "Decode session salt: %w"
	ErrorDecodeSessionSaltLength       = "Decode session salt length: %d"
	ErrorDecodeSessionNonce            = "Decode session nonce: %w"
	ErrorDecodeSessionNonceLength      = "Decode session nonce length: %d"
	ErrorDecodeSessionData             = "Decode session data: %w"
	ErrorDecryptSessionAuthentication  = "Decrypt session file %s: authentication failed"
	ErrorEncodeEncryptedSessionFile    = "Encode encrypted session file: %w"
	ErrorGenerateRandomBytes           = "Generate %s: %w"

	ErrorParseTelegramPublicKeyPEMNotFound = "Parse telegram public key: PEM block not found"
	ErrorParseTelegramPublicKey            = "Parse telegram public key: %w"

	ErrorTelegramAPIUninitialized = "Telegram API is not initialized"
	ErrorSourceChannelInputEmpty  = "Source channel input is empty"
	ErrorSourceParticipantEmpty   = "Source participant input is empty"
	ErrorSourceUserInputEmpty     = "Source user input is empty"

	ErrorWriteCacheFile                              = "Write cache file"
	ErrorLoadUserBio                                 = "Load user bio"
	ErrorLoadPremiumEmojiStatusPackTitleAndShortName = "Load premium emoji status pack title and short name"
	ErrorLoadCustomEmojiPackNames                    = "Load custom emoji pack names"
	ErrorHandleContentAuditMessage                   = "Handle content audit message"
)
